vich_uploader:
    db_driver: orm
    metadata:
        type: attribute

    mappings:
        recipe_images:
            uri_prefix: /assets/images
            upload_destination: '%kernel.project_dir%/public/assets/images'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
